Add configuration for websocket timeout
theintern/intern pull request #1176
Opened 2020-10-23 12:29 UTC by rhpijnacker

There are cases where it is useful/necessary to set the timeout on acknowledgments from the server when data is sent over the WebSocket. 
This PR makes it possible to configure this value.

2020-10-29 23:18 UTC, jason0x43 requested changes
This is looking good! A couple of the files ended up with Windows line endings -- could you convert those back to `\n`? (They make the diff huge.) Also, could you add the new socketTimeout option to the `schema in src/schemas/config.json`?

2020-10-29 23:18 UTC, jason0x43 commented on src/lib/channels/WebSocket.ts
> +    this.timeout = options.timeout || 10000;
Prefer `??` over `||`.

2020-10-30 12:47 UTC, jason0x43 commented
Thanks for fixing the schema and line endings.

Is there a need to use `||` in `this.timeout = options.timeout || 10000;` rather than `??`?

2020-10-30 12:58 UTC, rhpijnacker commented
When I use `??` it does not compile anymore.

2020-10-30 13:39 UTC, jason0x43 commented
Hmm...what version of TS are you building with (`??` is supported by TS 3.7+), and what error does it give you?

2020-10-30 16:21 UTC, rhpijnacker commented
Looks like I'm on "Version 3.5.2" (after doing a fresh `npm ci`).

The error is:
```
[0] 5:21:12 PM - [tsc:.] src/lib/channels/WebSocket.ts(21,37): error TS1109: Expression expected.
[0] 5:21:12 PM - [tsc:.] src/lib/channels/WebSocket.ts(21,44): error TS1005: ':' expected.
[0] 5:21:12 PM - Error running tsc:., exiting...
```

2020-11-02 15:03 UTC, jason0x43 commented
Hmmm...yeah, the TS version is set by intern-dev. Let's restore the original logic, then. While `??` is equivalent to the original, `||` is not (it won't allow a timeout of 0, for example).

2020-11-03 00:57 UTC, jason0x43 approved these changes

2020-11-03 00:57 UTC, merged